(llms) C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection>python bone_fracture.py
2025-07-10 17:18:10.119588: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them on orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-10 17:18:11.114413: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them on orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Descargando y extrayendo el dataset...
Traceback (most recent call last):
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 86, in <module>
    root_path = download_and_unzip_dataset()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 28, in download_and_unzip_dataset
    with zipfile.ZipFile(dataset_path, "r") as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\anaconda3\envs\llms\Lib\zipfile.py", line 1295, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Jorge\\.cache\\kagglehub\\datasets\\vuppalaadithyasairam\\bone-fracture-detection-using-xrays\\versions\\1'

(llms) C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection>python bone_fracture.py
Descargando y extrayendo el dataset...
Traceback (most recent call last):
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 78, in <module>
    root_path = download_and_unzip_dataset()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 5, in download_and_unzip_dataset
    dataset_path = kagglehub.dataset_download("vuppalaadithyasairam/bone-fracture-detection-using-xrays")
                   ^^^^^^^^^
NameError: name 'kagglehub' is not defined

(llms) C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection>python bone_fracture.py
Descargando y extrayendo el dataset...
Traceback (most recent call last):
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 78, in <module>
    root_path = download_and_unzip_dataset()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\Desktop\programacion\desarrollo_IA\Deep Learning\CNN\Bone Fracture detection\bone_fracture.py", line 5, in download_and_unzip_dataset
    dataset_path = kagglehub.dataset_download("vuppalaadithyasairam/bone-fracture-detection-using-xrays")
                   ^^^^^^^^^
NameError: name 'kagglehub' is not defined